git:
  depth: 5
language: scala
scala:
- 2.10.6
jdk:
- oraclejdk8
script: sbt clean compile
env:
  global:
  - secure: xUlXGpQOsNg5NYeIrq8ATJhnf7FkCKugMkT0lq0abvyXPzT8SA6UNSoxPKJZ1J7ntkzKoaN4jBsEChn5f0VXS7D4JlxmVOcLmc8fmd6W7KxyUXG7kfjLrop8inqp/U/TZN5WKblMmGqjV6FYuFG2oqc5SUuki2nrr8IpOcdj0vT8il/TiF1qgje0EfSGuyniJ2MrQ5TvExss9z7k+4Ujw01gNcPoUc5b5csjiQreym9c+49MWECb5Qwy1t96e7Icz/5hlSlRXCkcbO4wlO3R9dHs2Xzs78WbJ9Zft3wRnxQFeChHyB5JD6G1qLOtUQD6ChxoMgST4NKNrxFXiigUyMTW2HyA4WDypBQXLoQLD1lGQ1dXsqPQ+F9bPwFh/yO/k4F55BojkDPZHrDKZOjjlzIvDd+uwcHJkj4QjRb11+5M4RasyYM/Gd2oDg1OJylM1no1C/sm+kWtbKh0X4VKVFiTsiOocAM5DIzBPEQr6Hotw/UysTKChAVYmOzB+i3OrVEQrMbPrXi2HinK6JhIdYR5579acLZTQsGUM7cHLtoCHA/wHByf8OGobyydyt0Zhq4fNfIHnLV75M54UuzlIzEfGNQsXCnJn2ye9N4/UKxdn4Ydkk/OgYVMtjAT+q4xkxmXKnl3pdG0A2Yw2gEIT7SGrP5OK7nKI3fy3jGq8h4=
  - secure: Zo7RBNBSN/6DbY15/i6hCitLw8ypEL30Aq/Rs2+6747v9JH3q5v2Fu6yJGLvwzxfrSTP86dhBiktT6qtt3TRhdYjcGMRPN94Zyj9xBhD07WG2T5lSkl7qKiwiMkSEY4rzDXNtr3n9HlONJbMsrmdTP838kwNAExgQbino50P+s2A9B8M6zoExYo3mve65dxG0YkrD8/p1M2qcGpnU/+CNt6AGZH20Jz8a8fPNgFswsSKZwKSG7Q8hPAjSXM18XKmi9rUvkxT5ugwyZQJ9ySxN3oGDRHrGsZYpD9s8qAQjVY+vOtytH44pzdGKpBxyD7aQpDRYsH3ksX0isalBPu4/xvmH/nfPRGqVzeMtiWf7y3wtEuyQZSo1WDbSBrM2uHoDntyvXOpT0j1uY2DWYFt3eMr1oD6T8Cus6C0BiCN8Y6I5qAjDbPQEl+Qw62EKOeoA0FAql4OltnzLKnlWkXtBd/N7tfJlZbxhvKY7s6VOwcSpjiCeydiwu4ACaiSgdSMPtX2NjGbhANorzWd2FwVRU7U41FHqbuiolkiWKjilT5ysrkjicymORr6PM0M+9rz/pe9Ki9xYyebd5ZMGY7h4c2gtbyOTfP41i7UJ+bauAvCPd9eezaiC0AOU3lFg7WG0HtK83hLQaKC56EHYwMYMqt/ceRDUdTzh63ADfWGmxM=
